defaults:
  - _self_
  - gripper: panda

obj_file_name: fast_eta_objects_part_00.txt

max_rounds: 100

name: Fast_Data_Subset
# num target grasps to compute (will be checked in beginning)-> if enough exit
target_grasps: 5000

# collect grasps on sampling
sample_grasps: 800

# num grasps to collect from sampling + collision filtering till stability eval.
collect_grasps_till_eval: 100

# num grasps to collect till save
collect_grasps_till_save: 100

# object id name
object_id: 0

# force per impulse
force: 150.0 #200.0

hydra:
  job:
    chdir: False
