# Copyright (c) 2025 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

defaults:
  - _self_
  - env: clutter_table
  - gripper: panda_gelsight_mini

save_tactile: True
visualize: False
steps_close: 150
steps_lift: 500
lift_dist: 0.3
render_interval: 1

num_images: 200
id: 0
input_id: "0"

hydra:
  job:
    chdir: False
